### PR TITLE
add benchmarks for `pull-pushable`

### PR DESCRIPTION
**Pull request by ahdinosaur**
@Hypercubed @yoshuawuyts hey another bench :bar_chart: 

results [here](https://gist.github.com/ahdinosaur/8dea427c4e15eaff57ec7e422c91d8ef)

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
@ahdinosaur this part of results looks off - https://gist.github.com/ahdinosaur/8dea427c4e15eaff57ec7e422c91d8ef#emit-one-value---one-listener

**Comment by yoshuawuyts** [comment]
side note: ahh shame they're slow 😞 - wonder if we could make them faster? cc/ @dominictarr

**Comment by ahdinosaur** [comment]
i've been thinking,

`push-stream` is UDP (fire and forget)
`pull-stream` (as `pull-pushable`) is TCP (buffered in order)

`push-stream` is so simple it's fast
`pull-stream` is a better concept but not optimized

**Comment by yoshuawuyts** [comment]
@ahdinosaur ahh yeah I like that analogy

**Comment by dominictarr** [comment]
of course it's gonna be slower than a thing that does less. that said, pull-pushable was intended as a fallback... I try to avoid using it if possible. I never tried to optimize it.

you could probably get it to bench better by say, never pushing to the internal array if there is already a callback waiting https://github.com/pull-stream/pull-pushable/blob/master/index.js#L36

**Pull request merged**
